# Generated by Django 3.1.5 on 2021-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=70, verbose_name='Наименование товара')),
                ('item', models.CharField(max_length=70, verbose_name='Наименование товара')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма сделки')),
                ('quantity', models.IntegerField(verbose_name='Колличество товара, шт')),
                ('date', models.DateTimeField(verbose_name='Дата и время регистрации сделки')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
